### ISSUE TITLE
Upgrade to python3?

### ISSUE THREAD

**Issue by quinao** [alexandreblin/python-can-monitor#1]
Thank you for this project, it helped me a lot.
I ported it to python3, are you interested?
(This needed very few changes.)

**Comment by alexandreblin** [comment]
Yes, don't hesitate to send a pull request!

**Comment by quinao** [comment]
OK, do you want to drop python2 or keep both python2 and python3?

**Comment by alexandreblin** [comment]
I think `master` should be the python 3. I merged your pull request (#2) and created a `python2` branch pointing to the previous commit just in case someone needs it. Thanks again!
